name: 'Generate PDF'

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'src/**'

  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: 'Install Puppeteer dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 libgbm1

      - name: 'Install NPM dependencies'
        run: npm install --prefix misc

      - name: 'Generate PDF'
        run: node ./misc/generate-pdf.js

      - name: 'Upload PDF to Artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: generated-pdf
          path: resume.pdf

      - name: 'Commit PDF'
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add resume.pdf
          git commit -m "Generated PDF"
          git push
